# frozen_string_literal: true

source "https://rubygems.org"

gem 'elasticsearch', '~> 6.8.0'
gem 'aws-sdk-ssm'
gem 'aws-sdk-dynamodb'
gem 'pdf-reader'
gem 'redcarpet'
gem 'require_all'
gem 'rexml'
gem 'ruby-ddp-client', git: 'https://github.com/maths22/ruby-ddp-client'

gem 'chronic'
